### ISSUE TITLE
When can we expect python code for clinspacy?

### ISSUE THREAD

**Issue by Raghu17s** [ML4LHS/clinspacy#7]
Hey,

clinspacy seems to be interesting with Scisapcy, UMLS, CUI, and all. 
I would like to know, can we expect python wrapper for clinspacy.

**Comment by kdpsingh** [comment]
Hi @Raghu17s, there are no plans to bring clinspacy to Python. I'm sure it's possible to port to Python (since the underlying packages are all Python-based). Happy to help if you're interested in this.

Will close for now.
