### ISSUE TITLE
Partial Results and Certain Strings not Working

### ISSUE THREAD

**Issue by yzhang1337** [ML4LHS/clinspacy#9]
Hi there,

I recently ran ClinSpacy on a database full of video titles of surgical procedures and found that for some video titles most if not all CUI's that should be identified were. However, certain strings such as "Lymph node biopsy" were found to have no CUI's but upon searching in the Metathesaurus Browser there are several associated CUI's. 

I tried running these "missed titles" through clinspacy both by specifying within the dataframe but also just as a string. I tried both at default threshold and .70.

Is there something that I may be missing? 

Thanks!

**Comment by kdpsingh** [comment]
Thanks for the message. Under the hood, clinspacy is using the scispacy "large" language model, which is responsible for mapping phrases to UMLS CUIs.

Because clinspacy isn't directly doing any mapping to UMLS, there's not much I can do to improve mappings other than switching to a different spacy-compatible language model, for which I haven't found any good alternatives.

So as of now, I would say that fixing these mappings are out of the scope of clinspacy because clinspacy wraps other packages for this functionality.

You might want to enter some of the problematic phrases directly into the scispacy demo site to make sure the same issue is occurring there: You can see a demo of scispacy here: https://scispacy.apps.allenai.org

If the scispacy demo mapping are different, let me know and I'll re-open this issue to see if there's something wrong on my end.

**Comment by yzhang1337** [comment]
Thanks for getting back to me! So I ran a few strings through SciSpacy demo that had yielded no results with ClinSpacy. (This is also with "Show only top entity per mention" checked, and I did not change other settings besides model name and mention threshold.)

I understand that .70 is the min threshold in ClinSpacy and I had also played around with the "medium" model at 70% which performed similarly to the "large" model at 70%.


| string                                                                        | en\_core\_sci\_lg \(mention threshold \.99\) | en\_core\_sci\_lg \(mention threshold \.70\)                               | en\_core\_sci\_med \(\.99\)                                                                         | en\_core\_sci\_sm \(\.99\)                 |
|-------------------------------------------------------------------------------|----------------------------------------------|----------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------|--------------------------------------------|
| Lymph node biopsy                                                             | C0193842 \(Biopsy of lymph node\)            | C0193842 \(Biopsy of lymph node\)                                          | C0193842 \(Biopsy of lymph node\)                                                                   | C0193842 \(Biopsy of lymph node\)          |
| Modified Radical Mastectomy Carcinoma Breast Part 1                           | C0392747 \(Changing\)                        | C0392747 \(Changing\); C0024884 \(Mastectomy, Radical\)                    |                                                                                                     | C0024883 \(Modified radical mastectomy\)   |
| Thoracoabdominal Flap for Inflammatory Breast Cancer                          | C0278601 \(Inflammatory Breast Carcinoma\)   | C0444467 \(Thoracoabdominal\); C0278601 \(Inflammatory Breast Carcinoma\)	 | C0278601 \(Inflammatory Breast Carcinoma\)                                                          | C0278601 \(Inflammatory Breast Carcinoma\) |
| Inferior Gluteal Artery Flap Reconstruction Following Perineal Sinus Excision | C0561920 \(Perineal sinus\)                  | C0561920 \(Perineal sinus\)                                                | C0524865 \(Reconstructive Surgical Procedures\); C0561920 \(Perineal sinus\); C0728940 \(Excision\) |                                       |

Please let me know if there is anything else that I can do or provide that would help you!

**Comment by yzhang1337** [comment]
Below are also the raw I/O's of the code in case that it is useful!

```R
library(clinspacy) 
library(magrittr) # For the pipe %>%
library(dplyr)
library(tidytext)
library(rio)
clinspacy_init(use_linker = TRUE)

```

Output in console below:
```R
Initializing clinspacy using clinspacy_init()...
Checking if miniconda is installed...
Importing spacy...
Importing scispacy...
Importing medspacy modules...
Loading the en_core_sci_lg language model...
Loading the UMLS entity linker... (this may take a while)
Your CPU supports instructions that this binary was not compiled to use: AVX2
For maximum performance, you can install NMSLIB from sources 
pip install --no-binary :all: nmslib
Adding the UMLS entity linker to the spacy pipeline...
/Users/yilunzhang/Library/r-miniconda/envs/clinspacy/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator TfidfTransformer from version 0.20.3 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/Users/yilunzhang/Library/r-miniconda/envs/clinspacy/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator TfidfVectorizer from version 0.20.3 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
```

This error message has always been here but since I had figured that I was still getting output from most strings that it might be fine, but I figured I'd include this in case it helps.

Just for reference as well...

```R
clinspacy('Lymph node biopsy',threshold = 0.99)
```

```R
> clinspacy('Lymph node biopsy',threshold = 0.99)
Processing... Lymph node biopsy
  |==================================================================================================================================================| 100%
 [1] id              cui             entity          lemma           semantic_type   definition      is_family       is_historical   is_hypothetical
[10] is_negated      is_uncertain    section_title  
<0 rows> (or 0-length row.names)
```

```R
clinspacy('This patient has diabetes and CKD stage 3 but no HTN.',threshold = 0.99)
```
```R
> clinspacy('This patient has diabetes and CKD stage 3 but no HTN.',threshold = 0.99)
Processing... This patient has diabetes and CKD stage 3 but no HTN.
  |============================================================================================================================================| 100%
  id      cui      entity       lemma             semantic_type                      definition is_family is_historical is_hypothetical is_negated
1  1 C0030705     patient     patient Patient or Disabled Group                        Patients     FALSE         FALSE           FALSE      FALSE
2  1 C1578483     patient     patient           Idea or Concept         Report source - Patient     FALSE         FALSE           FALSE      FALSE
3  1 C1578484     patient     patient           Idea or Concept Relationship modifier - Patient     FALSE         FALSE           FALSE      FALSE
4  1 C1578486     patient     patient      Intellectual Product  Disabled Person Code - Patient     FALSE         FALSE           FALSE      FALSE
5  1 C1705908     patient     patient                  Organism              Veterinary Patient     FALSE         FALSE           FALSE      FALSE
6  1 C0011847    diabetes    diabetes       Disease or Syndrome                        Diabetes     FALSE         FALSE           FALSE      FALSE
7  1 C0011849    diabetes    diabetes       Disease or Syndrome               Diabetes Mellitus     FALSE         FALSE           FALSE      FALSE
8  1 C2316787 CKD stage 3 ckd stage 3       Disease or Syndrome  Chronic kidney disease stage 3     FALSE         FALSE           FALSE      FALSE
9  1 C0020538         HTN         htn       Disease or Syndrome            Hypertensive disease     FALSE         FALSE           FALSE       TRUE
  is_uncertain section_title
1        FALSE          <NA>
2        FALSE          <NA>
3        FALSE          <NA>
4        FALSE          <NA>
5        FALSE          <NA>
6        FALSE          <NA>
7        FALSE          <NA>
8        FALSE          <NA>
9        FALSE          <NA>
```

**Comment by kdpsingh** [comment]
Thank you so much for all the effort on your end in identifying *and* isolating the issue! Sorry for my delay in getting to this.

I figured out why this wasn't working and have fixed it in https://github.com/ML4LHS/clinspacy/commit/d6aff34828619005ec0f29042b8505f0a0de5fa6.

The issue was that some of the CUIs did not have matching semantic types and so were being excluded because of a line of code that filters in only those semantic types provided in the `clinspacy()` argument `semantic_types`. "lymph node biopsy" was one such example where it did not match a semantic type. I added `NA` to the default vector in the `semantic_types` arguments, and now the issue appears to be fixed.

Closing, but please reply to this issue if still not resolved and will re-open.
